import { Inter } from "next/font/google";
import "./globals.scss";
import { Suspense } from "react";
import { Header, HeaderLoading } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid min-h-svh w-full content-between bg-stone-50 dark:bg-neutral-900">
          <Suspense fallback={<HeaderLoading />}>
            <Header />
          </Suspense>
          <section className="px-8">{children}</section>
          <div className="bg-stone-300 p-8">1</div>
        </main>
      </body>
    </html>
  );
}
