import { Noto_Serif_Display, Victor_Mono } from "next/font/google";
import "./globals.scss";
import { Suspense } from "react";
import { Header, HeaderLoading } from "@/components/Header";

// const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Serif_Display({
  weight: ["200", "300", "400"],
  subsets: ["cyrillic-ext"],
  variable: "--secondary-font",
});

const victor = Victor_Mono({
  weight: ["200", "300", "400"],
  subsets: ["cyrillic-ext"],
  variable: "--subtitle-font",
});

export const metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${noto.variable} ${victor.variable}`}>
      <body>
        <Suspense fallback={<HeaderLoading />}>
          <Header />
        </Suspense>
        <main className="relative grid min-h-svh w-full content-between bg-stone-50 dark:bg-neutral-900">
          {children}
        </main>
        <div className="bg-stone-300 p-8">Footer</div>
      </body>
    </html>
  );
}
