import { Noto_Serif_Display, Victor_Mono, Ubuntu } from "next/font/google";
import "./globals.scss";
import { Suspense } from "react";
import { Header, HeaderLoading } from "@/components/Header";
import Footer from "@/components/Footer";

const noto = Noto_Serif_Display({
  display: "swap",
  weight: ["200", "300", "400"],
  subsets: ["cyrillic-ext"],
  variable: "--secondary-font",
});

const ubuntu = Ubuntu({
  display: "swap",
  weight: ["300", "400", "700"],
  subsets: ["cyrillic-ext"],
  variable: "--primary-font",
});

const victor = Victor_Mono({
  display: "auto",
  weight: ["200", "300", "400"],
  subsets: ["cyrillic-ext"],
  variable: "--subtitle-font",
});

export const metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${noto.variable} ${victor.variable} ${ubuntu.variable}`}
    >
      <body className="flex h-fit min-h-screen flex-col">
        <Suspense fallback={<HeaderLoading />}>
          <Header />
        </Suspense>
        <main className="relative grid w-full flex-grow ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
